GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/5f5de04b168a122976120081

###

DELETE http://localhost:3001/api/persons/5f601c19d2bd9aa5bc57dc4e

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Second Guy",
  "number": "99-122-343859"
}

###
PUT http://localhost:3001/api/persons/5f5e0c0a29c2f3d7fc01d8f3
Content-Type: application/json

{
  "number": "22-33-11111"
}